mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.fhit.test.microcity2.dao
#  configuration:
#    mapUnderscoreToCamelCase: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
